
# Using the pages generated by the author, the illustrator will create the shot framing and visuals for the story.

from dataclasses import dataclass, replace
import base64
import io
import json
import random
import re
from typing import Callable, Dict, List

from story_engine.lib.model_router.model_interface import ImageGenQuery, Capability
from story_engine.lib.model_router.query import Query
from story_engine.lib.model_router.router import ModelRouter
from story_engine.lib.model_router.retry import RetryConfig

from story_engine.lib.image_utils import download_image, image_to_base64
from story_engine.lib import output_formatting
from story_engine.elements import character
from story_engine.production.template_registry import templates

from PIL import Image

import logging

from story_engine.lib.quality_control.playbooks.batched_vision_solve import (
    BatchedVisionSolveConfig,
    BatchedVisionSolvePlaybook,
    VisionCritiqueRequest,
    VisionEvaluationItem,
)
from story_engine.lib.quality_control.types import (
    QCFeedbackWithChecklist,
    QCResult,
)
from story_engine.production.data_operators import (
    IllustratedScriptNode,
    PageOutlineNode,
    PageSketchOutput,
    PropSketch,
    ScriptNode,
    SketchOutput,
)
from story_engine.production.style_references import (
    load_style_reference,
    get_style_from_string,
    STYLE_SPECS,
)

logger = logging.getLogger(__name__)


@dataclass
class IllustratorConfig:
    """Configuration for the Illustrator."""

    illustration_style: str  # One of: abstract, cartoon, line_drawing, manga, moody, realistic, vintage, whimsical, wimmelbuch
    interface_type: str = "gemini_pro3_image"
    style_interface_type: str = (
        "together_flux2_dev_style_transfer"  # Interface for style_page (style transfer)
    )
    compaction_interface_type: str = "anthropic_haiku45"
    critique_interface_type: str = (
        "anthropic_sonnet4"  # Interface for critique_illustration (vision)
    )
    image_resolution: tuple[int, int] = (2048, 1536)  # iPad 4:3 aspect ratio

    retry_config: RetryConfig | None = None
    # Separate retry config for style transfer (Runware websocket is flaky)
    style_retry_config: RetryConfig | None = None


class Illustrator:
    """Creates visual elements for stories based on author's pages."""

    def __init__(self, config: IllustratorConfig) -> None:
        """Initialize the Illustrator with configuration.

        Args:
            config: IllustratorConfig containing interface type and illustration style
        """
        self.config = config
        self.router = ModelRouter(retry_config=self.config.retry_config)
        # Separate router for style transfer with more aggressive retries
        self.style_router = ModelRouter(
            retry_config=self.config.style_retry_config or self.config.retry_config
        )

    def update_config(self, **kwargs) -> None:
        """Update specific fields of the illustrator configuration.

        Args:
            **kwargs: Fields to update in the config (e.g., interface_type="new_type", illustration_style="whimsical")
        """
        self.config = replace(self.config, **kwargs)

    def _create_feedback_decoder(self) -> Callable[[str, str], QCFeedbackWithChecklist]:
        """Create a feedback decoder for QC playbooks."""
        def decoder(text: str, model: str) -> QCFeedbackWithChecklist:
            data = output_formatting.safe_json_decode(text)
            return QCFeedbackWithChecklist.from_flat_dict(data, model=model)
        return decoder

    def sketch(
        self,
        query: str,
        characters: List[character.Character] | None = None,
    ) -> SketchOutput:
        """Create a visual sketch based on the query and optional context.

        Uses _substitute_characters_in_shot to replace character names with
        compact visual descriptions, following the same pattern as sketch_page.

        Args:
            query: The sketch request or description
            characters: Optional list of characters to include

        Returns:
            SketchOutput: The generated sketch with prompt and image.
        """
        # Substitute character names with visual descriptions via LLM
        substituted_query, matched_characters, _ = (
            self._substitute_characters_in_shot(
                query, characters or [], key_props=None
            )
        )

        # Build reference images for matched characters
        reference_images: Dict[str, Image.Image] = {}
        for character_element in matched_characters:
            char_name = character_element.config.name
            if character_element.sketches:
                reference_images[char_name] = character_element.sketches[0]

        # Add style directive
        style_directive = (
            f"Children's {self.config.illustration_style} illustration style. "
            "Stylized, not photorealistic. "
        )
        query_text = style_directive + substituted_query

        image_query = ImageGenQuery(
            query_text=query_text,
            image_resolution=self.config.image_resolution,
            images=reference_images if reference_images else None,
            compaction_prompt=templates.render("illustrator/compact_prompt.system").to_flat_prompt(),
            compaction_model=self.config.compaction_interface_type,
            repetitions=2,
        )

        response = self.router.get_response(
            image_query, Capability.IMAGE_GEN, self.config.interface_type
        )

        return SketchOutput(prompt=query_text, image=response["images"][0])

    def sketch_styled(
        self,
        query: str,
        characters: List[character.Character] | None = None,
    ) -> SketchOutput:
        """Create a styled illustration in a single pass using the style reference image.

        Instead of generating a base image and then applying style transfer separately,
        this method passes the style reference image alongside the content prompt to the
        base image router, producing a styled image in one step.

        Follows the same pattern as _regenerate_illustration().

        Args:
            query: The sketch request or description
            characters: Optional list of characters to include

        Returns:
            SketchOutput: The generated styled sketch with prompt and image.
        """
        # Substitute character names with visual descriptions via LLM
        substituted_query, matched_characters, _ = (
            self._substitute_characters_in_shot(
                query, characters or [], key_props=None
            )
        )

        # Build reference images: style reference + character refs
        reference_images: Dict[str, Image.Image] = {}

        # Load the style reference image
        style_enum = get_style_from_string(self.config.illustration_style)
        style_spec = STYLE_SPECS[style_enum]
        reference_images["style_reference"] = load_style_reference(style_enum)

        # Add character reference images for matched characters
        for character_element in matched_characters:
            char_name = character_element.config.name
            if character_element.sketches:
                reference_images[char_name] = character_element.sketches[0]

        # Build prompt from registry template
        query_text = templates.render_text("illustrator/regenerate_image.user",
            content_prompt=substituted_query,
            illustration_style=self.config.illustration_style,
            style_spec=style_spec,
        )

        image_query = ImageGenQuery(
            query_text=query_text,
            image_resolution=self.config.image_resolution,
            images=reference_images,
            compaction_prompt=templates.render("illustrator/compact_prompt.system").to_flat_prompt(),
            compaction_model=self.config.compaction_interface_type,
            repetitions=2,
        )

        response = self.router.get_response(
            image_query, Capability.IMAGE_GEN, self.config.interface_type
        )

        return SketchOutput(prompt=query_text, image=response["images"][0])

    def _substitute_characters_in_shot(
        self,
        shot: str,
        characters: List[character.Character],
        key_props: Dict[str, str] | None = None,
    ) -> tuple[str, List[character.Character], List[str]]:
        """Use a language model to substitute character and prop references.

        This handles cases where characters may be referenced by variations of their
        name (e.g., "Luna the bunny" instead of just "Luna") and replaces them with
        compact visual descriptions suitable for image generation. It also substitutes
        key prop names with their compact visual descriptions.

        Args:
            shot: The shot description text to process (lens, lighting, poses, expressions)
            characters: List of all available characters
            key_props: Optional dict of prop name -> compact visual description

        Returns:
            Tuple of (enhanced shot description, list of matched characters, list of matched prop names)
        """
        if not characters and not key_props:
            return shot, [], []

        # Build the character mapping for the prompt
        char_mapping = {
            c.config.name: c.config.compact_visual_description or c.config.name
            for c in characters
        }

        # Merge prop mapping into entity mapping
        entity_mapping = {**char_mapping, **(key_props or {})}

        rules = (
            "Rules:\n"
            "1. Identify all character and prop references in the text (by name)\n"
            "2. Replace each name with their visual description from the entity_mapping\n"
            "3. Keep all other visual elements intact (lens type, poses, expressions)\n"
            "4. Output ONLY the updated description, nothing else"
        )

        query_parts = [
            f"Entity mapping (name -> visual description):\n{json.dumps(entity_mapping, indent=2)}",
            f"Shot description:\n{shot}",
        ]

        query = Query(
            system_prompt=(
                "You are a text processor for illustration prompts. Your task is to "
                "replace character names and prop names with visual descriptions.\n\n"
                + rules
            ),
            query_text="\n\n".join(query_parts),
            temperature=random.uniform(0.2, 0.4),
            top_p=random.uniform(0.6, 0.8),
            top_k=random.randint(20, 40),
            repetitions=2,
        )

        response = self.router.get_response(
            query, Capability.TEXT, self.config.compaction_interface_type
        )

        substituted_shot = response.get("text", shot).strip()

        # Determine which characters were matched by checking if their name was in the original shot
        # We check the original shot (not the substituted one) because the LLM paraphrases
        # the visual descriptions, so exact string matching on the output doesn't work
        matched_characters = [c for c in characters if c.config.name in shot]

        matched_prop_names = [name for name in (key_props or {}) if name in shot]

        return substituted_shot, matched_characters, matched_prop_names

    def sketch_prop(
        self,
        prop_name: str,
        compact_visual_description: str,
    ) -> SketchOutput:
        """Generate a reference image for a key prop.

        Creates a single 512x512 image of the prop on a plain white background
        in the configured illustration style.

        Args:
            prop_name: Display name of the prop.
            compact_visual_description: Short visual description for rendering.

        Returns:
            SketchOutput: The generated prop sketch with prompt and image.
        """
        style_enum = get_style_from_string(self.config.illustration_style)
        style_spec = STYLE_SPECS[style_enum]

        prompt_text = (
            f"A single {compact_visual_description} on a plain white background. "
            f"No characters, no scenery. "
            f"Children's {self.config.illustration_style} illustration style. "
            f"Stylized, not photorealistic. "
            f"Clear, centered, well-lit product shot.\n\n"
            f"Style spec:\n{style_spec}"
        )

        image_query = ImageGenQuery(
            query_text=prompt_text,
            image_resolution=(512, 512),
            repetitions=2,
        )

        response = self.router.get_response(
            image_query, Capability.IMAGE_GEN, self.config.interface_type
        )

        logger.info(f"Generated prop sketch for '{prop_name}'")
        return SketchOutput(prompt=prompt_text, image=response["images"][0])

    def extract_props_from_script(
        self,
        script_nodes: List[ScriptNode],
        characters: List[character.Character],
    ) -> Dict[str, PropSketch]:
        """Extract recurring key props from script and generate reference images.

        Uses an LLM to analyze all shot descriptions and identify visually
        distinctive props that appear across multiple pages, then generates
        a reference sketch for each prop via sketch_prop().

        Args:
            script_nodes: List of script nodes with shot descriptions.
            characters: List of characters (names excluded from prop output).

        Returns:
            Dict mapping prop name to PropSketch (visual_description, visual_description_prompt, image).
        """
        if not script_nodes:
            return {}

        # Build shot descriptions with page numbers for context
        shots_text = "\n".join(
            f"Page {node.page}: {node.shot}" for node in script_nodes
        )

        character_names = [c.config.name for c in characters]

        query = Query(
            structured_prompt=templates.render("illustrator/extract_props.system"),
            query_text=(
                f"Character names to EXCLUDE from props: {character_names}\n\n"
                f"Script shot descriptions:\n{shots_text}"
            ),
            temperature=random.uniform(0.4, 0.6),
            top_p=random.uniform(0.7, 0.9),
            top_k=random.randint(30, 50),
            repetitions=2,
        )

        response = self.router.get_response(
            query, Capability.TEXT, self.config.compaction_interface_type
        )

        try:
            data = output_formatting.safe_json_decode(response["text"])
            extracted = data.get("props", [])
            logger.info(f"Extracted {len(extracted)} key props from script")
        except Exception as e:
            logger.warning(f"Failed to parse prop extraction response: {e}")
            return {}

        # Generate reference sketches for each extracted prop
        prop_sketches: Dict[str, PropSketch] = {}
        for prop in extracted:
            name = prop.get("name", "")
            visual_desc = prop.get("visual_description", "")
            if not name or not visual_desc:
                continue

            try:
                sketch = self.sketch_prop(
                    prop_name=name,
                    compact_visual_description=visual_desc,
                )
                prop_sketches[name] = PropSketch(
                    visual_description=visual_desc,
                    image=sketch.image,
                )
            except Exception as e:
                logger.error(f"Failed to sketch prop '{name}': {e}")

        logger.info(f"Generated {len(prop_sketches)} prop sketches")
        return prop_sketches

    def sketch_page(
        self,
        shot: str,
        characters: List[character.Character],
        key_props: Dict[str, str] | None = None,
        prop_sketches: Dict[str, str] | None = None,
    ) -> PageSketchOutput:
        """Create a visual sketch based on the shot description.

        This generates the base illustration without art direction styling.
        Use style_page() to apply art direction to the resulting image.

        The shot comes from ScriptNode.shot which contains the image template
        with lens type, lighting, location context, and character poses/expressions.

        Args:
            shot: Image template from ScriptNode.shot (location context baked in)
            characters: List of all available characters (LLM identifies which are in shot)
            key_props: Optional dict of prop name -> compact visual description
            prop_sketches: Optional dict of prop name -> base64 encoded reference image

        Returns:
            PageSketchOutput: The generated sketch with prompt, image, and matched entities.
        """
        # Use LLM to substitute character and prop names with visual descriptions
        substituted_shot, matched_characters, matched_prop_names = (
            self._substitute_characters_in_shot(
                shot, characters, key_props=key_props
            )
        )

        # Build reference images for matched characters
        reference_images: Dict[str, Image.Image] = {}
        for character_element in matched_characters:
            char_name = character_element.config.name
            if len(character_element.sketches) == 0:
                raise ValueError(
                    f"Character {char_name} has no sketches for illustration."
                )
            if len(character_element.sketches) > 1:
                logger.warning(
                    f"Character {char_name} has multiple sketches; using the first one."
                )
            reference_images[char_name] = character_element.sketches[0]

        # Add prop reference images for matched props (handles both base64 and URLs)
        if prop_sketches and matched_prop_names:
            for prop_name in matched_prop_names:
                if prop_name in prop_sketches:
                    reference_images[prop_name] = download_image(
                        prop_sketches[prop_name]
                    )
                    logger.info(f"Attached reference image for prop: {prop_name}")

        # Add style directive to prevent photorealistic output
        # The actual style transfer happens in style_page(), but we guide the base
        # image model to produce stylized output that's easier to style-transfer
        style_directive = (
            f"Children's {self.config.illustration_style} illustration style. "
            "Stylized, not photorealistic. "
        )
        # The substituted_shot already has location context baked in
        query_text = style_directive + substituted_shot

        image_query = ImageGenQuery(
            query_text=query_text,
            image_resolution=self.config.image_resolution,
            images=reference_images if reference_images else None,
            compaction_prompt=templates.render("illustrator/compact_prompt.system").to_flat_prompt(),
            compaction_model=self.config.compaction_interface_type,
            repetitions=2,
        )

        response = self.router.get_response(
            image_query, Capability.IMAGE_GEN, self.config.interface_type
        )

        # Extract matched character and prop names for tracking
        matched_character_names = [c.config.name for c in matched_characters]

        return PageSketchOutput(
            prompt=query_text,
            image=response["images"][0],
            matched_character_names=matched_character_names,
            matched_prop_names=matched_prop_names,
        )

    def style_page(
        self,
        base_image: str | Image.Image,
        style_reference_override: str | Image.Image | None = None,
    ) -> SketchOutput:
        """Apply art direction styling to a base illustration.

        Takes a composed illustration and applies the configured illustration_style
        using a style reference image to create a stylized version.

        Args:
            base_image: The base illustration to style (PIL Image or base64 string)
            style_reference_override: Optional styled image to use as the style
                reference instead of loading the default style reference from storage.
                Use this to pass the styled title shot so all pages derive style
                from the same source (1-hop transfer instead of independent transfers).

        Returns:
            SketchOutput: The styled image with prompt and image data.
        """
        # Resolve the base image
        if isinstance(base_image, str):
            img_bytes = base64.b64decode(base_image)
            base_img = Image.open(io.BytesIO(img_bytes))
        else:
            base_img = base_image

        # Use override if provided, otherwise load default style reference
        style_enum = get_style_from_string(self.config.illustration_style)
        style_spec = STYLE_SPECS[style_enum]

        if style_reference_override is not None:
            style_reference = download_image(style_reference_override)
        else:
            style_reference = load_style_reference(style_enum)

        # Build images list: image 1 = base, image 2 = style reference
        images_list: List[Image.Image] = [base_img, style_reference]

        # Build styling prompt from registry template
        style_prompt = templates.render_text("illustrator/style_transfer.user",
            illustration_style=self.config.illustration_style,
            style_spec=style_spec,
        )

        # Build the styling query — preserve base image resolution
        image_query = ImageGenQuery(
            query_text=style_prompt,
            image_resolution=(base_img.width, base_img.height),
            images=images_list,
            repetitions=1,
        )

        response = self.style_router.get_response(
            image_query, Capability.IMAGE_GEN, self.config.style_interface_type
        )

        return SketchOutput(prompt=style_prompt, image=response["images"][0])

    def critique_illustration(
        self,
        illustrated_pages: List[IllustratedScriptNode],
        page_outlines: List[PageOutlineNode],
        characters: List[character.Character],
        prop_sketches: Dict[str, str] | None = None,
        max_workers: int = 4,
    ) -> QCResult:
        """Critique a batch of illustrated pages for consistency and alignment.

        Evaluates each page illustration against:
        - Story coherence: Does the image tell the story from the page?
        - Character consistency: Do characters match their reference images?
        - Prop consistency: Do props match their reference images?
        - Script alignment: Does the image match the shot description?

        Args:
            illustrated_pages: List of illustrated script nodes to critique.
            page_outlines: List of page outlines providing story context.
            characters: List of characters with reference sketches.
            prop_sketches: Optional dict of prop name -> base64 encoded reference image.
            max_workers: Maximum parallel workers for batch processing.

        Returns:
            QCResult with per-page feedback. Each checklist item includes:
            - Page number in the id (e.g., "page_3_char_inconsistency")
            - Brief edit instruction in description
            - Priority (P0=blocking, P1=important, P2=minor)
        """
        if not illustrated_pages:
            return QCResult(
                content="[]",
                approved=True,
                iterations=1,
                feedback_history=[],
            )

        # Build page outline lookup
        outline_by_page = {outline.page: outline for outline in page_outlines}

        # Build reference images dict from characters
        reference_images: Dict[str, Image.Image | str] = {}
        for char in characters:
            if char.sketches:
                # Use first sketch as reference
                reference_images[f"char_{char.config.name}"] = char.sketches[0]

        # Add prop references (handles both base64 and URLs from Firestore)
        if prop_sketches:
            for prop_name, prop_data in prop_sketches.items():
                reference_images[f"prop_{prop_name}"] = download_image(prop_data)

        # Build VisionEvaluationItem for each page
        evaluation_items: List[VisionEvaluationItem] = []
        for illustrated_node in illustrated_pages:
            page_num = illustrated_node.node.page
            script_node = illustrated_node.node

            # Get the image to evaluate (prefer critic-revised, then styled, then base)
            image_data = (
                illustrated_node.styled_image_url
                or illustrated_node.image_url
            )
            if not image_data:
                logger.warning(f"Page {page_num} has no image, skipping")
                continue

            # Convert image source to PIL Image (handles base64, URLs, etc.)
            page_image = download_image(image_data)

            # Get page outline for context
            outline = outline_by_page.get(page_num)
            outline_text = (
                outline.page_description if outline else "No outline available"
            )

            # Use stored matched entities from generation (not re-derived from shot text)
            char_refs_in_shot = [
                f"char_{name}" for name in illustrated_node.matched_character_names
            ]
            prop_refs_in_shot = [
                f"prop_{name}" for name in illustrated_node.matched_prop_names
            ]

            # Build per-page context using template from prompts
            page_context = templates.render_text("illustrator/critique.context",
                page_num=page_num,
                page_outline=outline_text,
                script_shot=script_node.shot,
                location=getattr(script_node, "location", ""),
            )

            evaluation_items.append(
                VisionEvaluationItem(
                    image=page_image,
                    reference_keys=char_refs_in_shot + prop_refs_in_shot,
                    id=f"page_{page_num}",
                    context=page_context,
                )
            )

        if not evaluation_items:
            return QCResult(
                content="[]",
                approved=True,
                iterations=1,
                feedback_history=[],
            )

        # Get control guide from prompt registry
        control_guide = templates.render("illustrator/critique.system")

        # Create the playbook config
        config = BatchedVisionSolveConfig(
            feedback_decoder=self._create_feedback_decoder(),
            model_interface=self.config.critique_interface_type,
            max_workers=max_workers,
        )

        # Create and run the playbook
        playbook = BatchedVisionSolvePlaybook(config, router=self.router)

        request = VisionCritiqueRequest(
            content="",  # Not used
            context="Evaluate illustration quality for children's picture book pages.",
            control_guide=control_guide,
            images=evaluation_items,
            reference_images=reference_images,
        )

        result = playbook.run(request, revise_fn=lambda x, y: x)

        logger.info(
            f"Illustration critique complete: {len(illustrated_pages)} pages, "
            f"approved={result.approved}"
        )

        return result

    def run_illustration_qc(
        self,
        illustrated_pages: List[IllustratedScriptNode],
        page_outlines: List[PageOutlineNode],
        characters: List[character.Character],
        prop_sketches: Dict[str, str] | None = None,
        key_props: Dict[str, str] | None = None,
        style_reference_override: str | Image.Image | None = None,
        max_iterations: int = 1,
        on_feedback: Callable[[QCFeedbackWithChecklist, int], None] | None = None,
        on_revision: Callable[[List[IllustratedScriptNode], int], None] | None = None,
        on_triage: Callable[[Dict[str, List[str]], int], None] | None = None,
    ) -> tuple[List[IllustratedScriptNode], QCResult]:
        """Run the full illustration QC loop: critique and revise until approved.

        This method handles the complete critique-revise cycle internally,
        similar to other QC methods like run_concept_qc and run_beats_qc.

        Args:
            illustrated_pages: List of illustrated script nodes to evaluate.
            page_outlines: List of page outlines providing story context.
            characters: List of characters with reference sketches.
            prop_sketches: Optional dict of prop name -> base64 encoded reference image.
            key_props: Optional dict of prop name -> compact visual description.
            style_reference_override: Optional styled title shot image for regeneration
                when style transfer catastrophically fails. Passed to _revise_illustration.
            max_iterations: Maximum number of critique-revise iterations.
            on_feedback: Optional callback invoked after each critique with
                (feedback, iteration). Iteration is 0-indexed.
            on_revision: Optional callback invoked after each revision with
                (revised_pages, iteration). Iteration is 0-indexed.

        Returns:
            Tuple of (final illustrated pages, QCResult with feedback history).
        """
        current_pages = illustrated_pages
        feedback_history: List[QCFeedbackWithChecklist] = []
        approved = False

        for iteration in range(max_iterations):
            logger.info(
                f"Illustration QC iteration {iteration + 1}/{max_iterations}"
            )

            # Critique current illustrations
            critique_result = self.critique_illustration(
                illustrated_pages=current_pages,
                page_outlines=page_outlines,
                characters=characters,
                prop_sketches=prop_sketches,
            )

            # Extract feedback from result
            if critique_result.feedback_history:
                feedback = critique_result.feedback_history[0]
                feedback_history.append(feedback)

                if on_feedback:
                    on_feedback(feedback, iteration)

                if feedback.action == "proceed":
                    logger.info("Illustration QC approved")
                    approved = True
                    break

                # Revise pages with issues, saving incrementally
                logger.info(
                    f"Revising illustrations based on {len(feedback.checklist)} feedback items"
                )
                all_triage_selections: Dict[str, List[str]] = {}
                for i, illustrated_node in enumerate(current_pages):
                    revised_node, page_triage = self._revise_illustration(
                        illustrated_node=illustrated_node,
                        feedback=feedback,
                        characters=characters,
                        prop_sketches=prop_sketches,
                        key_props=key_props,
                        style_reference_override=style_reference_override,
                    )
                    all_triage_selections.update(page_triage)
                    current_pages[i] = revised_node

                    if on_revision:
                        on_revision(current_pages, iteration)

                if on_triage:
                    on_triage(all_triage_selections, iteration)
            else:
                # No feedback returned, assume approved
                logger.info("No feedback returned, assuming approved")
                approved = True
                break

        if not approved:
            logger.warning(
                f"Illustration QC reached max iterations ({max_iterations}) "
                "without approval"
            )

        # Build final QCResult
        final_result = QCResult(
            content="",
            approved=approved,
            iterations=len(feedback_history),
            feedback_history=feedback_history,
        )

        return current_pages, final_result

    def _triage_checklist_items(
        self,
        page_num: int,
        items: list,
    ) -> list:
        """Use an LLM to select the top 3-5 most impactful checklist items to execute.

        Falls back to returning the first 5 items if the LLM call fails.
        """
        if len(items) <= 3:
            return items

        items_text = json.dumps(
            [
                {
                    "id": item.id,
                    "priority": item.priority,
                    "description": item.description,
                }
                for item in items
            ],
            indent=2,
        )

        query = Query(
            structured_prompt=templates.render("illustrator/triage.system"),
            query_text=f"Page {page_num} checklist items:\n{items_text}",
            temperature=0.1,
            repetitions=1,
        )

        response = self.router.get_response(
            query, Capability.TEXT, self.config.compaction_interface_type
        )

        try:
            selected_ids = output_formatting.safe_json_decode(response["text"])
            if isinstance(selected_ids, list):
                id_set = set(selected_ids)
                selected = [item for item in items if item.id in id_set]
                return selected[:5]
        except Exception as e:
            logger.warning(
                f"Page {page_num}: Triage failed, falling back to first 5 items: {e}"
            )

        return items[:5]

    def _revise_illustration(
        self,
        illustrated_node: IllustratedScriptNode,
        feedback: QCFeedbackWithChecklist,
        characters: List[character.Character],
        prop_sketches: Dict[str, str] | None = None,
        key_props: Dict[str, str] | None = None,
        style_reference_override: str | Image.Image | None = None,
    ) -> tuple[IllustratedScriptNode, Dict[str, List[str]]]:
        """Revise a single page illustration based on critique feedback.

        Internal method used by run_illustration_qc. Takes the original
        illustrated page and feedback, then edits the illustration in place.

        If the feedback contains a regeneration request (id ending with '_regenerate'),
        the page is regenerated from scratch using the styled title shot as a style
        reference instead of doing minor edits. This handles catastrophic style transfer
        failures where the image content is completely destroyed.

        Args:
            illustrated_node: The original illustrated page to revise.
            feedback: The critique feedback containing checklist items to address.
            characters: List of characters with reference sketches.
            prop_sketches: Optional dict of prop name -> base64 encoded reference image.
            key_props: Optional dict of prop name -> compact visual description.
            style_reference_override: Optional styled title shot for regeneration.

        Returns:
            Tuple of (updated IllustratedScriptNode, triage_selection dict mapping
            focusArea to selected item IDs for this page).
        """
        script_node = illustrated_node.node
        page_num = script_node.page

        # Extract checklist items for this specific page
        page_prefix = f"page_{page_num}_"
        page_items = [
            item
            for item in feedback.checklist
            if item.id.startswith(page_prefix) or item.focus_area == f"page_{page_num}"
        ]

        if not page_items:
            logger.info(f"Page {page_num}: No issues to address, keeping original")
            # Copy styled image as the critic-approved version so all pages
            # have a consistent critic_revised_image_url after QC.
            # Download and re-encode as base64 so Firestore upload creates a
            # separate _critic.png file (styled_image_url may already be a
            # storage path after a prior save, which upload_image_if_base64
            # would pass through unchanged).
            if not illustrated_node.critic_revised_image_url and illustrated_node.styled_image_url:
                styled_img = download_image(illustrated_node.styled_image_url)
                illustrated_node.critic_revised_image_url = image_to_base64(styled_img)
                illustrated_node.critic_revised_image_prompt = illustrated_node.styled_image_prompt
            return illustrated_node, {}

        # Check for regeneration request (style transfer catastrophic failure)
        regen_items = [item for item in page_items if item.id.endswith("_regenerate")]
        needs_regeneration = bool(regen_items)

        if needs_regeneration:
            triage_selection = {f"page_{page_num}": [item.id for item in regen_items]}
            return self._regenerate_illustration(
                illustrated_node=illustrated_node,
                characters=characters,
                prop_sketches=prop_sketches,
                style_reference_override=style_reference_override,
            ), triage_selection

        # Build edit instructions from checklist (strip page references like "[page_5]")
        def clean_description(desc: str) -> str:
            return re.sub(r"\[page_\d+\]\s*", "", desc)

        # Use LLM triage to select the top 3-5 most impactful items (P0 + high-impact P1s)
        incomplete_items = [item for item in page_items if not item.completed]
        actionable_items = self._triage_checklist_items(page_num, incomplete_items)
        triage_selection = {f"page_{page_num}": [item.id for item in actionable_items]}

        if not actionable_items:
            logger.info(f"Page {page_num}: No issues to address, keeping original")
            if not illustrated_node.critic_revised_image_url and illustrated_node.styled_image_url:
                styled_img = download_image(illustrated_node.styled_image_url)
                illustrated_node.critic_revised_image_url = image_to_base64(styled_img)
                illustrated_node.critic_revised_image_prompt = illustrated_node.styled_image_prompt
            return illustrated_node, triage_selection

        edit_instructions = "\n".join(
            f"- {clean_description(item.description)}"
            for item in actionable_items
        )

        # Get the image to edit (prefer critic-revised, then styled, then base)
        original_image_data = (
            illustrated_node.critic_revised_image_url
            or illustrated_node.styled_image_url
            or illustrated_node.image_url
        )
        if not original_image_data:
            logger.error(f"Page {page_num}: No original image to revise")
            return illustrated_node

        # Convert original image to PIL Image
        original_image = download_image(original_image_data)

        # Build reference images dict with original image first
        reference_images: Dict[str, Image.Image] = {"original": original_image}

        # Add character reference images for matched characters
        for char_name in illustrated_node.matched_character_names:
            char = next((c for c in characters if c.config.name == char_name), None)
            if char and char.sketches:
                reference_images[f"char_{char_name}"] = char.sketches[0]

        # Add prop reference images for matched props (handles both base64 and URLs)
        if prop_sketches:
            for prop_name in illustrated_node.matched_prop_names:
                if prop_name in prop_sketches:
                    reference_images[f"prop_{prop_name}"] = download_image(
                        prop_sketches[prop_name]
                    )

        # Get style spec for the prompt
        style_enum = get_style_from_string(self.config.illustration_style)
        style_spec = STYLE_SPECS[style_enum]

        # Build revision prompt from registry template
        revision_prompt = templates.render_text("illustrator/revise_image.user",
            edit_instructions=edit_instructions,
            illustration_style=self.config.illustration_style,
            style_spec=style_spec,
        )

        logger.info(
            f"Page {page_num}: Revising illustration based on {len(actionable_items)} triaged items"
        )

        try:
            image_query = ImageGenQuery(
                query_text=revision_prompt,
                image_resolution=self.config.image_resolution,
                images=reference_images,
                repetitions=2,
            )

            response = self.router.get_response(
                image_query, Capability.IMAGE_GEN, self.config.interface_type
            )

            revised_image = response["images"][0]

            logger.info(f"Page {page_num}: Revised illustration successfully")

            return IllustratedScriptNode(
                node=script_node,
                status="completed",
                image_url=illustrated_node.image_url,
                image_prompt=illustrated_node.image_prompt,
                styled_image_url=illustrated_node.styled_image_url,
                styled_image_prompt=illustrated_node.styled_image_prompt,
                critic_revised_image_url=revised_image,
                critic_revised_image_prompt=revision_prompt,
                matched_character_names=illustrated_node.matched_character_names,
                matched_prop_names=illustrated_node.matched_prop_names,
            ), triage_selection

        except Exception as e:
            logger.error(f"Page {page_num}: Error revising illustration: {e}")
            return IllustratedScriptNode(
                node=script_node,
                status="error",
                image_url=illustrated_node.image_url,
                image_prompt=illustrated_node.image_prompt,
                styled_image_url=illustrated_node.styled_image_url,
                styled_image_prompt=illustrated_node.styled_image_prompt,
                critic_revised_image_url=illustrated_node.critic_revised_image_url,
                critic_revised_image_prompt=illustrated_node.critic_revised_image_prompt,
                matched_character_names=illustrated_node.matched_character_names,
                matched_prop_names=illustrated_node.matched_prop_names,
                error=str(e),
            ), triage_selection

    def _regenerate_illustration(
        self,
        illustrated_node: IllustratedScriptNode,
        characters: List[character.Character],
        prop_sketches: Dict[str, str] | None = None,
        style_reference_override: str | Image.Image | None = None,
    ) -> IllustratedScriptNode:
        """Regenerate a page illustration from scratch after catastrophic style transfer failure.

        Instead of minor edits, this re-generates the image using the styled title shot
        as a style reference to preserve art direction while restoring the original content.

        Args:
            illustrated_node: The original illustrated page to regenerate.
            characters: List of characters with reference sketches.
            prop_sketches: Optional dict of prop name -> base64 encoded reference image.
            style_reference_override: Styled title shot image for style consistency.

        Returns:
            Updated IllustratedScriptNode with regenerated image.
        """
        script_node = illustrated_node.node
        page_num = script_node.page
        original_prompt = illustrated_node.image_prompt or script_node.shot

        logger.info(
            f"Page {page_num}: Regenerating illustration (style transfer failure detected)"
        )

        # Get style spec for the prompt
        style_enum = get_style_from_string(self.config.illustration_style)
        style_spec = STYLE_SPECS[style_enum]

        # Build reference images: title shot for style + character/prop refs for content
        reference_images: Dict[str, Image.Image] = {}

        if style_reference_override is not None:
            reference_images["style_reference"] = download_image(
                style_reference_override
            )
        else:
            reference_images["style_reference"] = load_style_reference(style_enum)

        for char_name in illustrated_node.matched_character_names:
            char = next((c for c in characters if c.config.name == char_name), None)
            if char and char.sketches:
                reference_images[f"char_{char_name}"] = char.sketches[0]

        if prop_sketches:
            for prop_name in illustrated_node.matched_prop_names:
                if prop_name in prop_sketches:
                    reference_images[f"prop_{prop_name}"] = download_image(
                        prop_sketches[prop_name]
                    )

        regeneration_prompt = templates.render_text("illustrator/regenerate_image.user",
            content_prompt=original_prompt,
            illustration_style=self.config.illustration_style,
            style_spec=style_spec,
        )

        try:
            image_query = ImageGenQuery(
                query_text=regeneration_prompt,
                image_resolution=self.config.image_resolution,
                images=reference_images if reference_images else None,
                compaction_prompt=templates.render(
                    "illustrator/compact_prompt.system"
                ).to_flat_prompt(),
                compaction_model=self.config.compaction_interface_type,
                repetitions=2,
            )

            response = self.router.get_response(
                image_query, Capability.IMAGE_GEN, self.config.interface_type
            )

            regenerated_image = response["images"][0]

            logger.info(f"Page {page_num}: Regenerated illustration successfully")

            return IllustratedScriptNode(
                node=script_node,
                status="completed",
                image_url=illustrated_node.image_url,
                image_prompt=illustrated_node.image_prompt,
                styled_image_url=illustrated_node.styled_image_url,
                styled_image_prompt=illustrated_node.styled_image_prompt,
                critic_revised_image_url=regenerated_image,
                critic_revised_image_prompt=regeneration_prompt,
                matched_character_names=illustrated_node.matched_character_names,
                matched_prop_names=illustrated_node.matched_prop_names,
            )

        except Exception as e:
            logger.error(
                f"Page {page_num}: Error regenerating illustration: {e}"
            )
            return IllustratedScriptNode(
                node=script_node,
                status="error",
                image_url=illustrated_node.image_url,
                image_prompt=illustrated_node.image_prompt,
                styled_image_url=illustrated_node.styled_image_url,
                styled_image_prompt=illustrated_node.styled_image_prompt,
                critic_revised_image_url=illustrated_node.critic_revised_image_url,
                critic_revised_image_prompt=illustrated_node.critic_revised_image_prompt,
                matched_character_names=illustrated_node.matched_character_names,
                matched_prop_names=illustrated_node.matched_prop_names,
                error=str(e),
            )
